In [8]:
from Neuron.Neuron import Neuron
from Neuron.NeuronLayer import NeuronLayer
from Neuron.NeuronNetwerk import NeuronNetwerk

import pandas as pd

In [9]:
invert_gate = Neuron([-1], 0.5)
and_gate = Neuron([0.5, 0.5], -1)
nor_gate = Neuron([-1, -1, -1], 0)

In [10]:
invert_results = pd.DataFrame(
    [
        [0, invert_gate.sigmoid_activation([0]), 1],
        [1, invert_gate.sigmoid_activation([1]), 0],
    ],
    columns= ["X1", "Result", "Target"]
)

invert_results

   X1    Result  Target
0   0  0.622459       1
1   1  0.377541       0

In [11]:
and_results = pd.DataFrame(
    [
        [0, 0, and_gate.sigmoid_activation([0, 0]), 0],
        [1, 0, and_gate.sigmoid_activation([1, 0]), 0],
        [0, 1, and_gate.sigmoid_activation([0, 1]), 0],
        [1, 1, and_gate.sigmoid_activation([1, 1]), 1],
    ],
    columns= ["X1","X2", "Result", "Target"]
)

and_results

   X1  X2    Result  Target
0   0   0  0.268941       0
1   1   0  0.377541       0
2   0   1  0.377541       0
3   1   1  0.500000       1

In [12]:
nor_results = pd.DataFrame(
    [
        [0, 0, 0, nor_gate.sigmoid_activation([0, 0, 0]), 1],
        [1, 0, 0, nor_gate.sigmoid_activation([1, 0, 0]), 0],
        [0, 1, 0, nor_gate.sigmoid_activation([0, 1, 0]), 0],
        [0, 0, 1, nor_gate.sigmoid_activation([0, 0, 1]), 0],
        [1, 1, 0, nor_gate.sigmoid_activation([1, 1, 0]), 0],
        [1, 0, 1, nor_gate.sigmoid_activation([1, 0, 1]), 0],
        [0, 1, 1, nor_gate.sigmoid_activation([0, 1, 1]), 0],
        [1, 1, 1, nor_gate.sigmoid_activation([1, 1, 1]), 0],
    ],
    columns= ["X1", "X2", "X3", "Result", "Target"]
)

nor_results

   X1  X2  X3    Result  Target
0   0   0   0  0.500000       1
1   1   0   0  0.268941       0
2   0   1   0  0.268941       0
3   0   0   1  0.268941       0
4   1   1   0  0.119203       0
5   1   0   1  0.119203       0
6   0   1   1  0.119203       0
7   1   1   1  0.047426       0

In [13]:
top_neuron = Neuron([0, 0], 0)
mid_neuron = Neuron([0, 0], 0)
bottom_neuron = Neuron([0, 0], 0)

carry = Neuron([0, 0, 0], 0)
Sum = Neuron([0, 0, 0], 0)

haddr_layer_1 = NeuronLayer([top_neuron, mid_neuron, bottom_neuron])
haddr_layer_2 = NeuronLayer([carry, Sum])

haddr = NeuronNetwerk([haddr_layer_1, haddr_layer_2])